### ISSUE TITLE
ECC Support

### ISSUE THREAD

**Issue by andrewpmartinez** [digitalbazaar/forge#580] opened 2018-05-02 13:03 UTC
It appears that node-forge does not support ecliptical curve cryptography.

Any plans to introduce it?

**Comment by dlongley** [comment] 2018-05-02 13:46
Forge supports [ed25519](https://github.com/digitalbazaar/forge#ed25519) (EdDSA), but not secp256k1/secp256r1 (ECDSA) yet. We would accept a PR to add support for the latter, but don't have any pressing needs for it or any internal resources to add it ourselves at the moment.

I'm going to close this because it's a duplicate of #532 -- where we're tracking ECC support.

**Closed by dlongley** 2018-05-02 13:46 UTC

**Comment by andrewpmartinez** [comment] 2018-05-02 16:46
Ahh I saw this line and assumed there was no support.

`  var oid = asn1.derToOid(capture.publicKeyOid);
  if(oid !== pki.oids.rsaEncryption) {
    throw new Error('Cannot read public key. OID is not RSA.');
  }`

**Comment by dlongley** [comment] 2018-05-02 18:35
Well, it is true that there isn't any ASN.1 support for ed25519 (or any other elliptic curve crypto) yet. Ed25519 keys can be transported much more simply as, for example, base58 and are new tech ... so often they don't need to fit into the older formats. We would accept a PR to add ASN.1/DER support for ed25519. This is related to #573.
