### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by xiuyu123123** [digitalbazaar/forge#1027] opened 2023-04-06 10:53 UTC
app.js错误:
 TypeError: Cannot read property 'crypto' of undefined
    at Object.t (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at e (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at Object.t (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at e (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at Object.t (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at e (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at Object.t (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at e (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at Object.t (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)
    at e (vendor.js?t=wechat&s=1680776449375&v=64a94e62456c2f5e6e877651680b0c61:8952)(env: macOS,mp,1.06.2301171; lib: 2.30.3)

**Comment by davidlehn** [comment] 2023-04-07 18:21
Duplicate of https://github.com/digitalbazaar/forge/issues/1028

**Closed by davidlehn** 2023-04-07 18:21 UTC
