### ISSUE TITLE
Can't get bytes during aes update

### ISSUE THREAD

**Issue by nekolab** [digitalbazaar/forge#219] opened 2015-02-25 14:32 UTC
Hello
I'm porting an app which using openssl to chrome app. 
Now I decide to use forge as AES encryptor instead of Openssl.

In this app, it sending data using a loop like:

```
cipher = new aes(iv)
while read():
    cipher.update(readContent)
    send(cipher.getBytes())
```

But I found in forge, I can just get encrypted data after calling finish().
The question is after calling finish(), I can't update cipher anymore.
Any ideas can let me get bytes without calling finish or restart cipher after finish?

**Comment by dlongley** [comment] 2015-02-25 15:34
The cipher API in forge exposes a buffer called `output` that stores encrypted data as it is generated. You can read from this buffer as you call `cipher.update` and before you call `cipher.finish` without issue. However, not every call to `cipher.update` will generate output (eg: you pass it too few bytes to output the next cipher block), so if that's a problem for your `send` API, then just check the size of the output buffer before trying to grab bytes from it. When you're done reading and encrypting the content, call `cipher.finish` and then send over the last block in `cipher.output`. See below:

```js
// start the cipher
var cipher = forge.cipher.createCipher('AES-CBC', key);
cipher.start({iv: iv});

while(someCondition) {
  cipher.update(forge.util.createBuffer(someText, 'utf8'));
  if(cipher.output.length() > 0) {
    send(cipher.output.getBytes());
  }
}

// finish encrypting and send final data
cipher.finish();
if(cipher.output.length() > 0) {
  send(cipher.output.getBytes());
}
```

Also, note that forge 0.6.x returns a binary-encoded string when you call `.getBytes()` on a buffer. If your `send` API needs the data in a Uint8Array instead, do this:

```js
send(s2a(cipher.output.getBytes()));

function s2a(str) {
  var view = new Uint8Array(str.length);
  for(var i = 0, j = str.length; i < j; i++) {
    view[i] = str.charCodeAt(i);
  }
  return view;
}
```

**Comment by meowlab** [comment] 2015-02-25 15:44
Thanks for your great help and notice!
Seems it's not a good way to test a cipher by feeding only two bytes to it :)

**Comment by meowlab** [comment] 2015-02-25 17:56
@dlongley Sorry to mention you again...
I just deep into the protocol and found something I didn't express clearly.

The protocol like a tcp pipe, it receive a message from one side, encrypt it, when another side receive this message, it will decrypt it.

When creating a pipe, a cipher will be created at the same time, on EACH send, libcrypto.EVP_CipherUpdate will be invoked, encrypt the data send from side A to side B.

Here comes the question, each send operation is "atomic", like side A send "hi" to start a connection,  side B should receive it immediately, and reply another "hi" to A, this makes a connection.

But now I can't get data immediately, if A cannot send encrypted "hi", B won't reply to him, so no further data will be generated,  A had no hope to get enough data to update.

And I cannot invoke finish() to let A send encrypted "hi", because further connection on this pipe relay on the previous update(), system works like below:

```
A  update("hi") -------> B
A  <----------------------- B
A update("other") ----> B
A  <----------------------- B
A update("more") ----> B
```

Are there any easy way to patch forge to force update works like libcrypto.EVP_CipherUpdate? I just tried some stupid way like enforce cipher._finish=true but not works correctly.

Thanks and sorry for my poor English!

**Comment by dlongley** [comment] 2015-02-25 18:51
@meowlab, what cipher are you using? AES-CBC?

By the way, forge's API works just like OpenSSL's.

For example, libcrypto.EVP_CipherUpdate (which works just like EVP_EncryptUpdate) may not produce any output bytes. See: [OpenSSL docs](https://www.openssl.org/docs/crypto/EVP_aes_256_ccm.html).

```
EVP_EncryptUpdate() encrypts inl bytes from the buffer in and writes
the encrypted version to out. This function can be called multiple times to
encrypt successive blocks of data. The amount of data written depends
on the block alignment of the encrypted data: as a result the amount of
data written may be anything from zero bytes to (inl + cipher_block_size - 1)
so out should contain sufficient room. The actual number of bytes written
is placed in outl.
```

Note "zero bytes" may be written. This has to do with how the underlying cipher algorithm works; it needs a certain number of bytes to fill up a block before it can produce an output block -- or it needs to pad the final block.

Based on what you've described above, it sounds like you've got a simple messaging protocol where you connect and then start sending short encrypted messages back and forth -- where each message triggers another message in response. The right way to do this would be to `start` the cipher for each message, consume the message with `update`, call `finish` and then call `getBytes` and send the encrypted message over. If you're using `libcrypto.EVP_CipherUpdate` on the server it's going to work the same way forge does, and you'll need to do something similar there.

If you want to send messages like you're suggesting above, you should encrypt the entire message and send it; then start a new cipher for the next message. This is essentially how SSL/TLS works; it encrypts an entire "record" (start cipher, update, finish) sends it, and then does the next "record".

**Comment by meowlab** [comment] 2015-02-27 10:18
@dlongley 
I want to use AES-CFB, AES-OFB and AES-CTR

I just checked EVP_EncryptUpdate's docs and understand it may write zero byte to output, but in my test, CFB, OFB and CTR always write encrypted data to output even plain text is only one or two bytes.

I think maybe CFB/OFB/CTR use IV as input of block cipher encryption, each time update content can full fill a block, so it can always has output, is my understand correct?

If it's correct, can forge have the same behavior?

**Comment by meowlab** [comment] 2015-03-02 15:58
Hello @dlongley , sorry to mention you again
I've just do some research in past few days about block cipher and stream cipher, I found CFB, OFB and CTR can works as a stream cipher, each update() can generate date, no need to wait for fulfill the block.

So I've implemented a stream cipher version of CFB:
```javascript
modes.cfb.prototype.start = function(options) {
  if(!('iv' in options)) {
    throw new Error('Invalid IV parameter.');
  }
  // use IV as first input
  this._iv = transformIV(options.iv);
  this._inBlock = this._iv.slice(0);
  this._cursor = this.blockSize;
};

modes.cfb.prototype.encrypt = function(input, output) {
  // encrypt block while cursor moves to the end of the block
  if (this._cursor === this.blockSize) {
    this._cursor = 0;
    this.cipher.encrypt(this._inBlock, this._outBlock);
    this._inBlock = [0, 0, 0, 0];
  }

  // XOR input with output, write input as output
  var endPos = Math.min(this.blockSize - this._cursor, input.length()) + this._cursor;
  for (var i = this._cursor, offset; i < endPos; ++i, ++this._cursor) {
    offset = (3 - (i % 4)) * 8;
    result = input.getByte() ^ (((this._outBlock[0|i/4]) & (0xFF << offset)) >>> offset);
    this._inBlock[0|i/4] |= result << offset;
    output.putByte(result);
  }
};

modes.cfb.prototype.decrypt = function(input, output) {
  // encrypt block (CFB always uses encryption mode)
  if (this._cursor === this.blockSize) {
    this._cursor = 0;
    this.cipher.encrypt(this._inBlock, this._outBlock);
    this._inBlock = [0, 0, 0, 0];
  }

  // XOR input with output
  var endPos = Math.min(this.blockSize - this._cursor, input.length()) + this._cursor;
  for (var i = this._cursor, offset, cipherText; i < endPos; ++i, ++this._cursor) {
    offset = (3 - (i % 4)) * 8;
    cipherText = input.getByte();
    this._inBlock[0|i/4] |= cipherText << offset;
    output.putByte(cipherText ^ (((this._outBlock[0|i/4]) & (0xFF << offset)) >>> offset));
  }
};
```

Do you think is it good for forge to switch CFB, OFB and CTR from block cipher to stream cipher?

If you think that's okay, feel free to tell me any thing you find is not good for merge, I'm willing to try my best to fix it and implement the OFB and CTR version of stream cipher.

Thanks!

**Comment by dlongley** [comment] 2015-03-02 19:13
Hi @meowlab -- we'd be fine with updating the implementations for CFB, OFB, and CTR to allow reading partial blocks. The only downside is reduced performance; which would be nice to measure, however, I think it would be worth supporting the feature regardless (and I don't expect it to be a dramatic reduction in speed).

There may need to be some other minor fixes to `cipher.js` (in addition to `cipherModes.js`) to accomplish what you're trying to do. In any case, we'd be happy to accept a PR that supports reading partial blocks to better support more fine-grained streaming like you're interested in.

**Comment by meowlab** [comment] 2015-03-03 15:59
Just a question:
I found some negative number in inBlock and outBlock, they are created by function getInt32(), but in the comment it says getInt32() returns a unsigned int.

I believe the negative number is comes from this.data.charCodeAt(this.read) << 24, it the highest bit of number is 1, it will return a negative value, like 0xa0 << 24 returns -1610612736.

Dose the getIntxx() returns negative is  by design? Thanks~

**Comment by meowlab** [comment] 2015-03-03 16:40
First patch for CFB mode has been pushed to my fork:
https://github.com/meowlab/forge/commit/08179342ddb49c70a8ed7711df281228f02d8d0f

Please review and let me know if anything is not meet the qualification.

**Comment by dlongley** [comment] 2015-03-03 18:21
@meowlab, re: signed vs. unsigned integers, I'll have to look more closely to see if that's a documentation error or a code error; it seems more likely to be a documentation error as the code functions properly. I suspect that function was being used for optimization purposes as an unsigned shift was unnecessary.

re: the patch - it looks like it's probably technically correct, but it seems like it's going to be doing a lot more work than the previous implementation. You could probably get the same result (output partial blocks down to a single byte) by doing your bitwise ops on zero-filled 32-bit integers and then truncating to the proper output size (which might be a single byte) instead of doing byte-by-byte ops for the whole block. Does that make sense?

If you don't have time to do that you can make a PR as is, but I'll either want to take some time to measure performance difference or change it a bit to do fewer ops before pulling it in. I may also do some code formatting/var name tweaking. I'm a bit swamped right now so I can't look further right away.

In any case, thanks for doing this work!

**Comment by meowlab** [comment] 2015-03-04 16:53
Hello @dlongley 
I've also considered about "bitwise ops to 32bit then truncate to fit size"(I called it batch stream mode), I also tried to implement it before I switched to "byte-to-byte" mode, it took me about two days and still have issue when doing encrypt, it's too complex, so I give up and try to implement "byte-to-byte" mode.

Today I spent a half day to clear my mind, finally I've implemented it on correct way, but I still think it's too complex, easy to cause bug, hard to maintain, and may not be much quicker because it need a great number of calculation to generate a zero-filled integers.

The batch stream mode has been implemented on branch batch-stream-mode, you can see it here: https://github.com/meowlab/forge/tree/byte-stream-mode

And the "byte-to-byte" mode has been implemented on branch byte-stream-mode, you can see it here: https://github.com/meowlab/forge/tree/byte-stream-mode

In my personal test, they can all works correctly, both on forge nodejs test and my self test case, and unfortunately, the batch stream is slower then byte-to-byte mode. In my self test case, it tooks 0.7-0.8 ms for "block mode" (the code on master branch now) to encrypt 5568 bytes when using AES-CFB-256, and about 1.1-1.2 ms for "byte-to-byte mode" to encrypt same bytes.

The "batch stream" mode tooks 2.5 - 2.6 ms on encrypt same thing. I think the huge amount of pre-calculation for a block tooks too much time.

So, in my personal opinion, I prefer to use "byte-to-byte" mode, it's easy to understand, easy to maintain, low bug possibility and a bit faster than current implementation of "batch stream mode".

I will create two pull request for each implementation later, so you can choice one to merge or close both, hope it won't disturb you. If you have some spare time in future, feel free to tell me if you have good idea to reduce the encrypt / decrypt time, I will try my best to make it better.

Thanks and sorry for my poor English ; )

**Comment by dlongley** [comment] 2015-03-04 17:04
Hi @meowlab, thanks for all your work! I'll look into both PRs when I get a chance, I'm just quite busy at the moment. I do see that the "batch stream mode" version looks quite complex. I'll see if there's a simpler way to implement it when I get a chance. Thanks for providing timing information as well; it looks like there's a ~50% performance decrease with byte-to-byte mode. Hopefully that can be improved on without the code getting too complex (I'll look into it). Thanks again; all or some portion of this work will get into forge when I can explore this issue further.

**Comment by dlongley** [comment] 2015-04-06 03:25
I managed to implement partial block processing in CFB mode without any performance degradation when you are processing data that is greater than or equal to a full block. In other words, existing applications shouldn't see any significant performance degradation. The implementation is fairly simple as well. When processing partial blocks there is some performance decline, as to be expected. Once I have time to clean things up and copy the implementation over to OFB and CTR modes, I'll merge it into the master branch.

**Comment by meowlab** [comment] 2015-04-07 02:00
Thanks for your great work! I think your implementation is better than mine!
I'm willing to test it after you implement all mode, thanks!

**Comment by dlongley** [comment] 2015-04-08 02:03
@meowlab, CFB, OFB, and CTR modes now support partial block encryption and decryption. GCM supports partial block encryption only due to algorithmic/implementation details. Feel free to test :)

**Comment by meowlab** [comment] 2015-04-13 06:09
I've write a test in my application, let forge encrypt around 300MB data (1500bytes per round, 1024 * 200 round) and measure the time cost.
The result is not stable, sometimes can be 4-5MB/s but sometimes can be 2-3MB/s
But my byte-to-byte mode is always a bit (less than 1MB/s) faster that latest 0.6.23.
It seems impossible but it actually happens, I can reproduce it on my PC everytime.

Could you use some 'official' way to test the performance?

**Comment by dlongley** [comment] 2015-04-13 14:55
@meowlab, make sure that when you're testing you're also running the code on the same core on your machine (eg: on linux, `taskset 0x1 <executable>`).

Could you include the code of your test application so I can run it here?

**Comment by meowlab** [comment] 2015-06-10 17:23
@dlongley Hello I'm back~
Here is my testcase:
```javascript

var forge_30  = require('./0.6.30/forge.min.js'),
    forge_mod = require('./my-mod/forge.min.js');

var test_forge = function(forge) {
    var iv = forge.random.getBytesSync(16),
        key = forge.random.getBytesSync(32),
        bytes = forge.random.getBytesSync(1500);

    var cipher = forge.cipher.createCipher('AES-CBC', key);
    cipher.start({iv: iv});

    var start = new Date().getTime();
    for (var i = 0; i < 1024 * 200; ++i) {
        cipher.update(forge.util.createBuffer(bytes));
        bytes = cipher.output.getBytes();
    }
    var end = new Date().getTime();
    return 150 * 2000 / (end - start);
};

var forge_30_time = 0,
    forge_mod_time = 0;

for (var i = 0; i < 10; ++i) {
    forge_mod_time += test_forge(forge_mod.forge);
    forge_30_time  += test_forge(forge_30.forge);
}

console.log("My mod: ", forge_mod_time / 10);
console.log("Forge 0.6.30: ", forge_30_time / 10);
```
"My mod" is compiled based on https://github.com/digitalbazaar/forge/pull/224
"Forge 0.6.30" is compiled based on tag 0.6.30
All builds set `forge.disableNativeCode` to `false` since it cannot work on NodeJS

Result:
```
$ taskset 02 node test.js
My mod:  17.593837385638583
Forge 0.6.30:  17.379492324821282

$ taskset 02 node test.js
My mod:  17.36520345307118
Forge 0.6.30:  17.074925631481243

$ taskset 02 node test.js
My mod:  17.62195893933095
Forge 0.6.30:  17.45889982269485

$ taskset 02 node test.js
My mod:  17.59626983942379
Forge 0.6.30:  17.468287662207498

$ taskset 02 node test.js
My mod:  17.559607638125566
Forge 0.6.30:  17.391539895717454
```
Enviroment: iojs v2.2.1

**Comment by dlongley** [comment] 2017-01-11 16:43
Closing as significantly out of date. Optimizations to existing algorithm implementations are welcome, but we need many more benchmark tests first to be written for the library in general.

**Closed by dlongley** 2017-01-11 16:43 UTC
