### ISSUE TITLE
forge does not load

### ISSUE THREAD

**Issue by ofersadgat** [digitalbazaar/forge#215] opened 2015-01-30 05:22 UTC
With node.js, adding forge causes the javascript to halt on load with the error: "Uncaught Error: Cannot find module './aes'"

To reproduce:

``` bash
npm install gulp gulp-browserify gulp-concat node-forge react reactify
```

gulpfile.js:

```
var gulp         = require('gulp');
var browserify   = require('gulp-browserify');
var concat       = require('gulp-concat');


gulp.task('browserify', function(){
    return gulp.src('src/js/main.jsx')
                .pipe(browserify({transform: 'reactify'}))
                .pipe(concat('out.js'))
                .pipe(gulp.dest('dist/js'));
})

gulp.task('html', function(){
    return gulp.src('src/index.html')
                .pipe(gulp.dest('dist'));
});

gulp.task('default', ['browserify', 'html']);
```

src/index.html:

``` html
<HTML>
  <head>

  </head>
  <body>
    <div id="client"></div>
    <script src="js/out.js"></script>
  </body>
</HTML>
```

src/js/main.jsx:

``` javascript
var React   = require('react');
var forge    = require('node-forge');

var App = React.createClass({
    render: function(){
        return (
            <div>There is no cake.</div>
        );
    }
});

React.render(<App />, document.getElementById('client'));
```

**Comment by dlongley** [comment] 2015-01-30 15:48
This is a problem we'd like to get fixed, see #126.

**Comment by iamolivinius** [comment] 2015-03-03 11:55
Is there any way around this issue until the "new build system" is live?

**Comment by dlongley** [comment] 2015-03-03 15:24
@iamolivinius, unfortunately I'm swamped so I haven't had time to investigate getting forge working with browserify. Does anyone else have a good workaround?

There's always the option to load forge just as a regular bundled script (or a set of scripts) or use requirejs for the time being. Obviously that's not ideal in browserify environments, but it does work.

**Comment by iamolivinius** [comment] 2015-03-03 15:44
Right now I use an `npm install` alias to bower forge and run its build script. There is no prebuild bundle in the repo, right? 

I'm not so confident with all the module formats but my first idea would be to make use of the ES6 module syntax and https://github.com/esnext/es6-module-transpiler to transpile into the different module formats.

**Comment by ofersadgat** [comment] 2015-03-03 17:20
Yes, what I ended up doing was exactly as @dlongley said: I am including the bundled version and it seems to be working fine.

**Comment by dlongley** [comment] 2015-03-03 18:28
> There is no prebuild bundle in the repo, right?

Right.

**Comment by henry74** [comment] 2015-03-08 04:54
I have installed forge using bower and I'm trying to use it in an angularjs application.  Do I need to inject anything to get it working?  Right now it's failing with the following error:
```
TypeError: Cannot read property 'getBytesSync' of undefined
```
The line causing the problem is:
```
var salt = forge.random.getBytesSync(128);
```
It appears forge is a valid object, but random is not...

**Comment by mikemaccana** [comment] 2015-07-13 11:53
Hrm was hoping to test node-forge as an alternate to asn1js / pkijs and also getting `Cannot find module './aes'` Any updates on the new build system? I'd like to avoid hacking the module if possible.

**Comment by acasajus** [comment] 2015-07-19 21:04
I'm also interested in this. Is there any news on this?

**Comment by dlongley** [comment] 2015-07-30 21:02
@mikemaccana,

Can you provide more details about how you're loading forge so we can try and help determine the problem? Can you generate and use the bundled version like others have?

@acasajus,

No updates on this front yet, but further discussion/ideas over at #126 or PRs are welcome.

**Comment by RaedsLab** [comment] 2016-05-03 08:35
:bump: 

Is there an update on this ?

**Comment by dlongley** [comment] 2016-05-03 13:13
@davidlehn -- can we get an update over at #357?

**Comment by RaedsLab** [comment] 2016-05-03 13:54
@dlongley : This is easily avoidable on the user part, by decoupling what they want to do with browserify form forge and then using forge.min.js in the browser to get the same behavior. 

It took me 5 minutes of copy pasting.

**Comment by jbollam** [comment] 2016-07-12 18:44
@henry74  use forge.min.js file this iwll resolve your error.

**Comment by davidlehn** [comment] 2017-02-07 22:53
0.7.0 was released with a new build system which should address this issue.  Reopen if it's still a problem.

**Closed by davidlehn** 2017-02-07 22:53 UTC
