### ISSUE TITLE
forge.pki.rsa.generateKeyPair() is slow and speed is random

### ISSUE THREAD

**Issue by bendiy** [digitalbazaar/forge#125] opened 2014-06-10 20:49 UTC
I've been working with forge.pki.rsa.generateKeyPair() and have noticed the time it takes to generate a keypair is all over the map. The fastest I've had it run is 978ms with one worker. The slowest is 33167ms with five workers.

Here's an example:
``` javascipt
forge.pki.rsa.generateKeyPair({bits: 2048, workers: 5}, function(err, keypair) {
  console.log(keypair);
}
```
Comparing it with the npm module `ursa`, there's a huge difference. Ursa is a wrapper for openssl, so I expect it to be faster, but I also don't expect forge.pki.rsa.generateKeyPair() to take 5 to 10 seconds.

Here's an example I put together that compares the performance with one worker:
http://runnable.com/U5dptzsL5dhk9jAo/forge-vs-ursa-for-node-js-and-keypair
Visit that link and click on "Run". Results are something like:
```
genKeyUrsa 1.1: 1402432950578
genKeyUrsa 1.2: 1402432950772
genKeyUrsa time: 194
genKeyForge 1.1: 1402432950773
genKeyForge 1.2: 1402432958892
genKeyForge time: 8119
```
Run it a few times to see how much the results vary.

Here's a command line gist you can run locally:
https://gist.github.com/bendiy/6a0133786f64766fecce

Ursa's `ursa.generatePrivateKey()` defaults to 2048, so these functions should be doing the same thing.

**Comment by dlongley** [comment] 2016-06-28 17:36
Closed as duplicate of #285.

**Closed by dlongley** 2016-06-28 17:36 UTC
