### ISSUE TITLE
Delete of an unqualified identifier in strict mode

### ISSUE THREAD

**Issue by homerjam** [digitalbazaar/forge#396] opened 2016-05-09 17:40 UTC
Hi there,

I'm getting this error when trying to use strict mode with `node --use_strict`

```
node-forge/js/forge.js:53
delete define;
           ^^^^^^
SyntaxError: Delete of an unqualified identifier in strict mode.

**Comment by dlongley** [comment] 2016-05-09 20:47
Duplicate of #333.

**Closed by dlongley** 2016-05-09 20:47 UTC

**Comment by homerjam** [comment] 2016-05-09 21:08
Ah, apologies. I did look, obviously not hard enough :blush:
